# Generated by Django 4.1.7 on 2023-02-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_active_account_is_stff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_stff',
            new_name='is_staff',
        ),
    ]
